swagger: '2.0'
info:
  description: API Documentation of Parallel custom modules
  title: Parallel Swagger Documentation
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
host: localhost:1317
schemes:
  - http
  - https
tags:
  - name: Asset
    description: Everything about Assets
    externalDocs:
      description: Find out more
      url: http://parallel.one
  - name: Oracle
    description: Everything about Oracle
    externalDocs:
      description: Find out more
      url: http://parallel.one
  - name: Vault
    description: Everything about Vault
    externalDocs:
      description: Find out more
      url: http://parallel.one
paths:

definitions:

